"""Separator-based dynamic programme for 3-D hypervolume subset selection.

Implements the n^{O(sqrt k)} algorithm of

    K. Bringmann, S. Cabello, M. T. M. Emmerich,
    "Maximum Volume Subset Selection for Anchored Boxes", SoCG 2017
    (arXiv:1803.00849), Section 4.

The recursion computes  Psi_comp(S, D, l)  for valid tuples (S, D, l):

    S   points already selected,
    D   an S-compliant polygonal domain (a union of triangles of T(S)),
    l   number of points that may still be selected inside D x R.

    Psi(S, D, l) = Phi_comp(S, D, l)                         if l <= base
                 = max over valid partitions pi of
                   sum_{(S', D_i, l_i) in pi} Psi(S', D_i, l_i)   otherwise,

where a valid partition consists of a set S_0 of O(sqrt(|S|+l)) further
points, S' = S + S_0, a subdivision of D into (S')-compliant domains D_i and
budgets l_i <= 2l/3 with |S_0| + sum l_i = l.  The partitions are generated by
short simple cycles gamma of T(S') with P_gamma \\ S = S_0 (the alternative
suggested in the proof of Theorem 4.6).

Every value produced by the recursion is the volume of a feasible selection
restricted to D x R, hence a lower bound (Lemma 4.3); it is the exact optimum
as soon as the separator of Lemma 4.4 is among the enumerated cycles.
"""
from __future__ import annotations

import math
import time
from dataclasses import dataclass, field
from itertools import combinations

import numpy as np

from . import _kernels as K


@dataclass
class SeparatorParams:
    """Constants hidden in the O(.)-notation of the paper.

    base      : a tuple with l <= ceil(c_base * sqrt(k)) is solved by enumeration.
    cycle     : separator cycles have at most ceil(c_cycle * sqrt(|S|+l)) vertices.
    s0        : |S_0| <= ceil(c_s0 * sqrt(|S|+l)).
    allow_trivial : also use the valid partitions with a single domain D_1 = D
                (they only need |S_0| >= l/3); with False, only partitions
                induced by a cycle that really cuts D are used.
    prune     : branch-and-bound on the choice of S_0 (greedy incumbent +
                submodular upper bound).  Never changes the optimum that is found.
    theory    : use the constants for which exactness is proven (Miller's
                cycle separator: |gamma| <= 4 sqrt(|V(T)|), |V(T)| <= 5(|S|+l)+5,
                |P_gamma| <= 2|gamma|).  For every k of practical size these are
                so large that the algorithm degenerates to enumeration.
    """
    c_base: float = 1.0
    c_cycle: float = 2.5
    c_s0: float = 1.0
    allow_trivial: bool = True
    theory: bool = False
    prune: bool = True

    def base(self, k):
        return max(1, math.ceil(self.c_base * math.sqrt(k)))

    def cycle_len(self, m):
        if self.theory:
            return int(4.0 * math.sqrt(5 * m + 5))
        return max(3, math.ceil(self.c_cycle * math.sqrt(m)))

    def s0_max(self, m):
        if self.theory:
            return 2 * self.cycle_len(m)
        return max(1, math.ceil(self.c_s0 * math.sqrt(m)))


@dataclass
class Result:
    subset: np.ndarray          # indices into the input array
    hypervolume: float          # exact hypervolume of `subset` (independent computation)
    dp_value: float             # Psi(emptyset, sigma, k), in input units
    stats: dict = field(default_factory=dict)


def to_anchored(F, ref):
    """Minimisation objective vectors + reference point -> anchored boxes."""
    return np.asarray(ref, float)[None, :] - np.asarray(F, float)


def nondominated(P):
    """Indices of the points of P (maximisation) not weakly dominated by another."""
    n = len(P)
    keep = []
    for a in range(n):
        dom = False
        for b in range(n):
            if b != a and np.all(P[b] >= P[a]) and (np.any(P[b] > P[a]) or b < a):
                dom = True
                break
        if not dom:
            keep.append(a)
    return np.array(keep, np.int64)


class _Solver:
    def __init__(self, P, k, params):
        self.n = n = len(P)
        self.k = k
        self.params = params
        scale = P.max(axis=0)
        Q = P / scale
        for c in range(3):            # general position (paper: p + i*eps*(1,1,1))
            if len(np.unique(Q[:, c])) < n:
                Q[:, c] = Q[:, c] + 1e-9 * np.arange(1, n + 1)
        self.scale = float(np.prod(scale))
        self.X, self.Y, self.Z = (np.ascontiguousarray(Q[:, c]) for c in range(3))
        self.gi = np.empty(n, np.int64)
        self.gj = np.empty(n, np.int64)
        self.gi[np.argsort(self.X)] = np.arange(n) + 2
        self.gj[np.argsort(self.Y)] = np.arange(n) + 2
        M = max(self.X.max(), self.Y.max())
        mg = 0.25 * M
        self.gx = np.concatenate([[-mg, 0.0], np.sort(self.X), [M + mg]])
        self.gy = np.concatenate([[-mg, 0.0], np.sort(self.Y), [M + mg]])
        self.W = n + 3
        self.pt_of_gi = np.full(n + 3, -1, np.int64)
        self.pt_of_gj = np.full(n + 3, -1, np.int64)
        self.pt_of_gi[self.gi] = np.arange(n)
        self.pt_of_gj[self.gj] = np.arange(n)
        NV = self.W * self.W
        if NV * NV > 40_000_000:
            raise ValueError("n too large for the stamped edge table (n <= ~75)")
        self.estamp = np.zeros(NV * NV, np.int32)
        self.etri = np.zeros(NV * NV, np.int32)
        self.bstamp = np.zeros(NV * NV, np.int32)
        self.ectr = np.zeros(1, np.int64)
        self.bctr = np.zeros(1, np.int64)
        self.base = params.base(k)
        self.memo = {}
        self.stats = dict(tuples=0, base_cases=0, base_subsets=0, recursive_tuples=0,
                          s0_tried=0, s0_compliant=0, s0_pruned=0, cycles=0, partitions=0, partitions_pruned=0,
                          max_S=0, max_depth=0)

    # -- small helpers -------------------------------------------------------
    def _sel(self, smask):
        return np.array([p for p in range(self.n) if (smask >> p) & 1], np.int64)

    def _build(self, sel):
        m = len(sel)
        if 10 * m + 16 > K.MAX_TRIANGLES:
            raise ValueError("selection too large for the triangle bit masks")
        tri = np.empty((10 * m + 16, 3), np.int64)
        owner = np.empty(10 * m + 16, np.int64)
        F = K.build_T(sel, m, self.gi, self.gj, self.Z, self.n, self.gx, self.gy, tri, owner)
        return tri, owner, F

    # -- the recursion ---------------------------------------------------------
    def psi(self, smask, dkey, ell, depth=0):
        """Returns (Psi(S, D, ell), bit mask of the selected Q)."""
        key = (smask, dkey, ell)
        hit = self.memo.get(key)
        if hit is not None:
            return hit
        st = self.stats
        n, W = self.n, self.W
        sel = self._sel(smask)
        mS = len(sel)
        tri, owner, F, inside, bed, cand = K.prepare(
            sel, mS, np.frombuffer(dkey, np.int64), self.gi, self.gj, self.Z, n, self.gx,
            self.gy, self.estamp, self.etri, self.ectr)
        skip = np.zeros(n, np.bool_)
        skip[sel] = True
        nc = len(cand)
        if ell > nc:
            res = self.psi(smask, dkey, nc, depth)
            self.memo[key] = res
            return res
        st["tuples"] += 1
        st["max_S"] = max(st["max_S"], mS)
        st["max_depth"] = max(st["max_depth"], depth)

        if ell <= self.base:
            val, q, qs, tried = K.base_case(sel, mS, cand, nc, ell, bed, self.gi, self.gj,
                                            self.Z, n, self.gx, self.gy, self.estamp,
                                            self.etri, self.ectr, self.bstamp, self.bctr)
            st["base_cases"] += 1
            st["base_subsets"] += tried
            qmask = 0
            for p in q[:qs]:
                qmask |= 1 << int(p)
            res = (val, qmask)
            self.memo[key] = res
            return res

        st["recursive_tuples"] += 1
        par = self.params
        L = par.cycle_len(mS + ell)
        smax = min(ell, par.s0_max(mS + ell))
        cap = (2 * ell) // 3
        NVV = W * W
        stack = np.empty(10 * (mS + smax) + 16, np.int64)
        inside2 = np.zeros(10 * (mS + smax) + 16, np.bool_)
        pos = np.full(n, -1, np.int64)

        # Q = emptyset is always feasible (D is S-compliant)
        bs = K.mark_boundary(bed, NVV, self.bstamp, self.bctr)
        _, best = K.eval_in_domain(tri, owner, F, W, self.gx, self.gy, self.Z, bed, bs,
                                   self.estamp, self.etri, self.ectr, self.bstamp,
                                   inside2, stack)
        best_q = 0
        if par.prune:
            gv, gq = K.greedy_in_domain(sel, mS, cand, nc, ell, bed, self.gi, self.gj, self.Z,
                                        n, self.gx, self.gy, self.estamp, self.etri,
                                        self.ectr, self.bstamp, self.bctr)
            if gv > best:
                best, best_q = gv, sum(1 << int(p) for p in gq)

        for s in range(0, smax + 1):
            ell2 = ell - s
            for S0 in combinations(cand.tolist(), s):
                st["s0_tried"] += 1
                sel2 = np.concatenate([sel, np.array(S0, np.int64)])
                tri2, owner2, F2 = self._build(sel2)
                # nested psi calls re-use the boundary stamp table
                bs = K.mark_boundary(bed, NVV, self.bstamp, self.bctr)
                ok, vol2 = K.eval_in_domain(tri2, owner2, F2, W, self.gx, self.gy, self.Z,
                                            bed, bs, self.estamp, self.etri, self.ectr,
                                            self.bstamp, inside2, stack)
                if not ok:                      # D is not (S + S_0)-compliant
                    continue
                st["s0_compliant"] += 1
                ins2 = inside2[:F2].copy()
                skip2 = skip.copy()
                skip2[list(S0)] = True
                loc2 = K.locate_points(tri2, F2, W, self.gx, self.gy, ins2, self.gi, self.gj,
                                       skip2, n)
                if par.prune:
                    ub, gain_pt = K.s0_upper_bound(tri2, owner2, F2, W, self.gx, self.gy, self.X, self.Y,
                                          self.Z, ins2, sel2, mS + s, loc2, n, ell2, vol2)
                    if ub <= best * (1.0 + 1e-12):
                        st["s0_pruned"] += 1
                        continue
                smask2 = smask
                s0mask = 0
                for p in S0:
                    s0mask |= 1 << p
                smask2 |= s0mask

                if par.allow_trivial and s > 0 and ell2 <= cap:
                    if ell2 == 0:
                        v, q = vol2, 0
                    else:
                        dkey2 = K.flags_to_words(ins2, F2).tobytes()
                        v, q = self.psi(smask2, dkey2, ell2, depth + 1)
                    if v > best:
                        best, best_q = v, s0mask | q
                    if ell2 == 0:
                        continue

                verts, ltri, nbr = K.topology(tri2, F2, W, self.estamp, self.etri, self.ectr)
                pos[:] = -1
                for a, p in enumerate(S0):
                    pos[p] = a
                cover = K.vertex_cover_bits(verts, W, self.pt_of_gi, self.pt_of_gj, pos)
                full = (1 << s) - 1
                parts, ncyc = K.enumerate_partitions(ltri, nbr, F2, len(verts), ins2, cover,
                                                     full, L, ell2 == 0)
                st["cycles"] += int(ncyc)
                if len(parts) == 0:
                    continue
                if ell2 == 0:                   # a separator through all of S_0 exists
                    if vol2 > best:
                        best, best_q = vol2, s0mask
                    continue
                for words in parts:
                    st["partitions"] += 1
                    ncomp, cnt, cvol, cwords, pcomp = K.split_components(
                        tri2, owner2, nbr, F2, W, self.gx, self.gy, self.Z, ins2, words,
                        loc2, n)
                    if par.prune:
                        ub = K.partition_upper_bound(ncomp, cnt, cvol, pcomp, gain_pt, n,
                                                     cap, ell2)
                        if ub <= best * (1.0 + 1e-12):
                            st["partitions_pruned"] += 1
                            continue
                    v, q = self._combine(smask2, ell2, cap, ncomp, cnt, cvol, cwords, depth)
                    if v > best:
                        best, best_q = v, s0mask | q
        res = (best, best_q)
        self.memo[key] = res
        return res

    def _combine(self, smask2, ell2, cap, ncomp, cnt, cvol, cwords, depth):
        """max  sum_i Psi(S', D_i, l_i)  s.t.  sum l_i = l', l_i <= 2l/3  (max-plus knapsack)."""
        const = 0.0
        comps = []
        for c in range(ncomp):
            if cnt[c] == 0:
                const += cvol[c]
            else:
                comps.append(c)
        his = [min(cap, int(cnt[c]), ell2) for c in comps]
        tot = min(ell2, sum(his))
        NEG = -1.0
        table = {0: (const, 0)}
        rest = sum(his)
        for c, hi in zip(comps, his):
            rest -= hi
            dkey = cwords[c].tobytes()
            new = {}
            for used, (v0, q0) in table.items():
                lo = max(0, tot - used - rest)
                for j in range(lo, min(hi, tot - used) + 1):
                    if j == 0:
                        v, q = cvol[c], 0
                    else:
                        v, q = self.psi(smask2, dkey, j, depth + 1)
                    cur = new.get(used + j)
                    if cur is None or v0 + v > cur[0]:
                        new[used + j] = (v0 + v, q0 | q)
            table = new
        return table.get(tot, (NEG, 0))


def solve(points, k, reference=None, params=None):
    """Exact 3-D hypervolume subset selection by the separator DP.

    points    : (n,3) array.  With ``reference`` given: minimisation objective
                vectors, hypervolume w.r.t. the reference point.  Otherwise
                maximisation points spanning boxes anchored at the origin.
    k         : subset size.
    """
    params = params or SeparatorParams()
    P = np.asarray(points, float)
    if reference is not None:
        P = to_anchored(P, reference)
    if P.ndim != 2 or P.shape[1] != 3:
        raise ValueError("points must be an (n,3) array")
    valid = np.flatnonzero(np.all(P > 0, axis=1))
    nd = valid[nondominated(P[valid])]
    t0 = time.perf_counter()
    if k >= len(nd):
        subset = nd
        dp = None
        stats = {}
    else:
        solver = _Solver(P[nd], k, params)
        sigma = np.zeros(K.WORDS, np.int64)
        sigma[0] = 3                                  # T(emptyset): the two triangles of sigma
        val, qmask = solver.psi(0, sigma.tobytes(), k)
        chosen = [p for p in range(len(nd)) if (qmask >> p) & 1]
        # With constants below the proven ones the recursion may find no valid
        # partition that spends the whole budget; complete such a set greedily.
        padded = k - len(chosen)
        while len(chosen) < k:
            rest = [p for p in range(len(nd)) if p not in chosen]
            gains = [K.hv3d(solver.X, solver.Y, solver.Z, np.array(chosen + [p], np.int64),
                            len(chosen) + 1) for p in rest]
            chosen.append(rest[int(np.argmax(gains))])
        subset = nd[chosen]
        dp = val * solver.scale
        stats = dict(solver.stats)
        stats["memo_entries"] = len(solver.memo)
        stats["base_threshold"] = solver.base
        stats["greedy_padded"] = padded
    stats["time"] = time.perf_counter() - t0
    X, Y, Z = (np.ascontiguousarray(P[:, c]) for c in range(3))
    hv = K.hv3d(X, Y, Z, np.asarray(subset, np.int64), len(subset))
    return Result(np.sort(subset), hv, hv if dp is None else dp, stats)


def solve_brute_force(points, k, reference=None):
    """Reference: enumerate all k-subsets of the non-dominated points."""
    P = np.asarray(points, float)
    if reference is not None:
        P = to_anchored(P, reference)
    valid = np.flatnonzero(np.all(P > 0, axis=1))
    nd = valid[nondominated(P[valid])]
    t0 = time.perf_counter()
    X, Y, Z = (np.ascontiguousarray(P[nd, c]) for c in range(3))
    kk = min(k, len(nd))
    hv, comb, count = K.brute_force(X, Y, Z, len(nd), kk)
    return Result(np.sort(nd[comb]), hv, hv, dict(subsets=int(count), time=time.perf_counter() - t0))


def solve_greedy(points, k, reference=None):
    P = np.asarray(points, float)
    if reference is not None:
        P = to_anchored(P, reference)
    valid = np.flatnonzero(np.all(P > 0, axis=1))
    nd = valid[nondominated(P[valid])]
    t0 = time.perf_counter()
    X, Y, Z = (np.ascontiguousarray(P[nd, c]) for c in range(3))
    hv, comb = K.greedy(X, Y, Z, len(nd), min(k, len(nd)))
    return Result(np.sort(nd[comb]), hv, hv, dict(time=time.perf_counter() - t0))
